sudo: true
dist: trusty

language: cpp

before_install:
  - ./.travis/install-dependencies.sh 

script:
  - ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/src/bionitio-build/bionitio-cpp -d functional_tests/test_data
  - ./.travis/unit-test.sh
