sudo: true
dist: xenial
services:
  - docker
language: cpp

before_install:
  - docker build -t bionitio-cpp .

script:
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-cpp
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-cpp -p bionitio-cpp -d /bionitio/functional_tests/test_data -v
