sudo: true
dist: xenial
services:
  - docker
language: cpp

before_install:
  - docker build -t bionitio-cpp .
    #- ./.travis/install-dependencies.sh 

script:
  #- ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/src/bionitio-build/bionitio-cpp -d functional_tests/test_data
  #- ./.travis/unit-test.sh
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-cpp
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-cpp -p bionitio -d /bionitio/functional_tests/test_data -v
